imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FlatbelFlatBundle/Resources/config/config.yml"}

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    photo_directory: 'uploads/photos/'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    default_locale: ru
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    form:
        resources:
            - 'FlatbelFlatBundle:Form:media_widgets.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 5.6
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: UTF8
        options:
          1002: 'SET NAMES UTF8'
        types:
          json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ApplicationSonataMediaBundle: ~
            SonataMediaBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    port:      "%mailer_port%"
#    encryption: "%mailer_encryption%"
    spool:     { type: memory }

#FOSUserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Flatbel\FlatBundle\Entity\User
    use_listener:           true
    use_flash_notifications: true
    use_authentication_listener: true
    use_username_form_type: true
#    model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    profile:
        form:
            type:               fos_user_profile # or 'fos_user_profile' on Symfony < 2.8
            name:               fos_user_profile_form
            validation_groups:  [Profile, Default]
    change_password:
        form:
            type:               fos_user_change_password # or 'fos_user_change_password' on Symfony < 2.8
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword, Default]
    registration:
        confirmation:
#            from_email: # Use this node only if you don't want the global email address for the confirmation email
#                address:        registration@flatbel.by
#                sender_name:    Registration
            enabled:    true # change to true for required email confirmation
            template:   '@FOSUser/Registration/email.txt.twig'
        form:
            type:               fos_user_registration # or 'fos_user_registration' on Symfony < 2.8
            name:               fos_user_registration_form
            validation_groups:  [Registration, Default]
    resetting:
        token_ttl: 86400
        email:
#            from_email: # Use this node only if you don't want the global email address for the resetting email
                                          #                address:        resetting@flatbel.by
                                          #                sender_name:    Resetting
            template:   email/password_resetting.email.twig
        form:
            type:               fos_user_resetting # or 'fos_user_resetting' on Symfony < 2.8
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]
    service:
        mailer:                 fos_user.mailer.default
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default

#SonataAdminBundle
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...
sonata_admin:
    security:
        handler: sonata.admin.security.handler.noop
    dashboard:
        groups:
            app.admin.group.admin:
                label: Администратор
                roles: [ ROLE_ADMIN, ROLE_SUPER_ADMIN]
            app.admin.group.user:
                label: Пользователь
                roles: [ ROLE_USER ]
    title:      Flatbel
    title_logo: Logo.png
    templates:
        layout:                         FlatbelFlatBundle:Admin:standard_layout.html.twig
        ajax:                           FlatbelFlatBundle:Admin:ajax_layout.html.twig
        list:                           FlatbelFlatBundle:Admin:CRUD/list.html.twig
        show:                           FlatbelFlatBundle:Admin:CRUD/show.html.twig
        show_compare:                   FlatbelFlatBundle:Admin:CRUD/show_compare.html.twig
        edit:                           FlatbelFlatBundle:Admin:CRUD/edit.html.twig
        history:                        FlatbelFlatBundle:Admin:CRUD/history.html.twig
        preview:                        FlatbelFlatBundle:Admin:CRUD/preview.html.twig
        delete:                         FlatbelFlatBundle:Admin:CRUD/delete.html.twig
        batch:                          FlatbelFlatBundle:Admin:CRUD/list__batch.html.twig
        acl:                            FlatbelFlatBundle:Admin:CRUD/acl.html.twig
        action:                         FlatbelFlatBundle:Admin:CRUD/action.html.twig
        select:                         FlatbelFlatBundle:Admin:CRUD/list__select.html.twig
        filter:                         FlatbelFlatBundle:Admin:Form/filter_admin_fields.html.twig
        dashboard:                      FlatbelFlatBundle:Admin:Core/dashboard.html.twig
        search:                         FlatbelFlatBundle:Admin:Core/search.html.twig
        batch_confirmation:             FlatbelFlatBundle:Admin:CRUD/batch_confirmation.html.twig
        inner_list_row:                 FlatbelFlatBundle:Admin:CRUD/list_inner_row.html.twig
        base_list_field:                FlatbelFlatBundle:Admin:CRUD/base_list_field.html.twig
        list_block:                     FlatbelFlatBundle:Admin:Block/block_admin_list.html.twig
        user_block:                     FlatbelFlatBundle:Admin:Core/user_block.html.twig
        add_block:                      FlatbelFlatBundle:Admin:Core/add_block.html.twig
        pager_links:                    FlatbelFlatBundle:Admin:Pager/links.html.twig
        pager_results:                  FlatbelFlatBundle:Admin:Pager/results.html.twig
        tab_menu_template:              FlatbelFlatBundle:Admin:Core/tab_menu_template.html.twig
        history_revision_timestamp:     FlatbelFlatBundle:Admin:CRUD/history_revision_timestamp.html.twig
        short_object_description:       FlatbelFlatBundle:Admin:Helper/short-object-description.html.twig
        search_result_block:            FlatbelFlatBundle:Admin:Block/block_search_result.html.twig
        action_create:                  FlatbelFlatBundle:Admin:CRUD/dashboard__action_create.html.twig
        button_acl:                     FlatbelFlatBundle:Admin:Button/acl_button.html.twig
        button_create:                  FlatbelFlatBundle:Admin:Button/create_button.html.twig
        button_edit:                    FlatbelFlatBundle:Admin:Button/edit_button.html.twig
        button_history:                 FlatbelFlatBundle:Admin:Button/history_button.html.twig
        button_list:                    FlatbelFlatBundle:Admin:Button/list_button.html.twig
        button_show:                    FlatbelFlatBundle:Admin:Button/show_button.html.twig

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [FlatbelFlatBundle]

    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js"
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css"
            filters: [cssrewrite]

        bootstrap_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"
            output: "fonts/glyphicons-halflings-regular.woff"

        jquery:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        flatphotos:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

sonata_seo:
    encoding:         UTF-8
    page:
        title:            Flatbel
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             foo bar
                description:          The description
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Flatbel
                'og:description':     A demo of the some rich bundles for your Symfony2 projects

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
#                'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"

ivory_google_map:
    map:
        api_key: AIzaSyB7yPhkSBY2GKqlY6UxkmSzAOjZDA2So3s
        language: "%locale%"