# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    FlatbelFlatFileUploader:
        class: Flatbel\FlatBundle\Service\FileUploader
        arguments:
            $targetDir: '%photo_directory%'

    admin.user:
        class: Flatbel\FlatBundle\Admin\UserAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\User,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Полтьзователи", group: "app.admin.group.admin" }
        public: true

    admin.flat:
        class: Flatbel\FlatBundle\Admin\FlatAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\Flat,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Квартиры Админ", group: "app.admin.group.admin" }
        public: true

    admin.admin:
        class: Flatbel\FlatBundle\Admin\AdminAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\Flat, FlatbelFlatBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Квартиры", group: "app.admin.group.user" }
        public: true

    admin.city:
        class: Flatbel\FlatBundle\Admin\CityAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\City,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Города", group: "app.admin.group.admin" }
        public: true

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
