# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    FlatbelFlatFileUploader:
        class: Flatbel\FlatBundle\Service\FileUploader
        arguments:
            $targetDir: '%photo_directory%'

    admin.user:
        class: Flatbel\FlatBundle\Admin\UserAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\User,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
