# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    FlatbelFlatFileUploader:
        class: Flatbel\FlatBundle\Service\FileUploader
        arguments:
            $targetDir: '%photo_directory%'

    admin.user:
        class: Flatbel\FlatBundle\Admin\UserAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\User,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "User", group: "app.admin.group.admin" }
        public: true
    admin.flat:
        class: Flatbel\FlatBundle\Admin\FlatAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\Flat,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Flat, group: "app.admin.group.admin" }

    admin.admin:
        class: Flatbel\FlatBundle\Admin\AdminAdmin
        arguments: [~, Flatbel\FlatBundle\Entity\Flat, FlatbelFlatBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Admin, group: "app.admin.group.user" }


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
