<?php

namespace Flatbel\FlatBundle\Entity\Repository;
use Composer\DependencyResolver\Request;


/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFlats($flattype, $numberofbeds, $metro, $limit)
    {
        $qb = $this->createQueryBuilder('f')
            ->select('f')
            ->addOrderBy('f.id', 'DESC');


        if (false == is_null($limit))
            $qb->setMaxResults($limit);

        if ($flattype != 'Не важно')
        {
            $qb->andWhere('f.flattype = :flattype')
                ->setParameter('flattype', $flattype);
        }
        if ($numberofbeds != 'Не важно')
        {
            $qb->andWhere('f.numberofbeds = :numberofbeds')
                ->setParameter('numberofbeds', $numberofbeds);
        }
        if ($metro != 'Не важно')
        {
            $qb->andWhere('f.metro = :metro')
                ->setParameter('metro', $metro);
        }


        return $qb->getQuery()
            ->getResult();
    }
}
