<?php

namespace Flatbel\FlatBundle\Entity\Repository;
use Composer\DependencyResolver\Request;


/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFlats($flattype, $numberofbeds, $metro, $limit, $city, $pricehour, $priceday)
    {
        $qb = $this->createQueryBuilder('f')
            ->select('f')
            ->addOrderBy('f.id', 'DESC');

        if ($flattype != 'Не важно')
        {
            $qb->andWhere('f.flattype = :flattype')
                ->setParameter('flattype', $flattype);
        }

        if ($numberofbeds != 'Не важно')
        {
            $qb->andWhere('f.numberofbeds = :numberofbeds')
                ->setParameter('numberofbeds', $numberofbeds);
        }

        if ($metro != 'Не важно')
        {
            $qb->andWhere('f.metro = :metro')
                ->setParameter('metro', $metro);
        }

        if (false == is_null($limit))
            $qb->setMaxResults($limit);


        if ($city != null)
        {
            $qb->andWhere('f.city = :city')
                ->setParameter('city', $city);
        }

        $qb -> andWhere('f.priceday BETWEEN :pricehour AND :priceday')
            ->setParameter('pricehour', $pricehour)
            ->setParameter('priceday', $priceday);

        return $qb->getQuery()
            ->getResult();
    }
}
