# src/Blogger/BlogBundle/Resources/config/routing.yml
FlatbelFlatBundle_homepage:
    path:     /
    defaults: { _controller: "FlatbelFlatBundle:Page:index" }
    requirements:
         methods:  GET


FlatbelFlatBundle_flat_create:
    path: /create
    defaults: { _controller: "FlatbelFlatBundle:Flat:create" }
    requirements:
        methods: POST

FlatbelFlatBundle_flat_show:
    path:  /{description}
    defaults: { _controller: "FlatbelFlatBundle:Flat:show" }
    requirements:
        methods:  GET

