# src/Blogger/BlogBundle/Resources/config/routing.yml
FlatbelFlatBundle_homepage:
    path:     /
    defaults: { _controller: "FlatbelFlatBundle:Page:index" }
    requirements:
         methods:  GET

FlatbelFlatBundle_register:
    path:     /register
    defaults: { _controller: "FlatbelFlatBundle:Page:register" }
    requirements:
         methods:  GET|POST