# src/Blogger/BlogBundle/Resources/config/routing.yml
FlatbelFlatBundle_homepage:
    path:     /
    defaults: { _controller: "FlatbelFlatBundle:Page:index" }
    requirements:
         methods:  POST

FlatbelFlatBundle_contact:
    path: /contact
    defaults: { _controller: "FlatbelFlatBundle:Page:contact"}
    requirements:
        methods: POST

FlatbelFlatBundle_flat_create:
    path: /create
    defaults: { _controller: "FlatbelFlatBundle:Flat:create" }
    requirements:
        methods: POST

FlatbelFlatBundle_flat_flats:
    path: /flats
    defaults: { _controller: "FlatbelFlatBundle:Flat:flats" }
    requirements:
        methods: POST

FlatbelFlatBundle_flat_show:
    path:  /flats/{description}id={id}
    defaults: { _controller: "FlatbelFlatBundle:Flat:show" }
    requirements:
        methods:  GET
        id: \d+


