services:
  acme_user.password_resetting:
        class: Flatbel\FlatBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

  flatbel_flat.uploadfile:
        class: Flatbel\FlatBundle\Service\FileUploader
        arguments:
            $targetDir: '%photo_directory%'

#    flatbel_flat.example:
#        class: Flatbel\FlatBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
